### PR TITLE
Use self

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by adamnemecek** [comment]
The errors seem to be stylistic.

**Comment by emilio** [comment]
This looks good, thanks! Could you run `cargo fmt` and squash your commits? That way it can be merged.

**Comment by adamnemecek** [comment]
Squash isn't doing quite what I expected.

**Comment by emilio** [comment]
Hmm, there's something really weird in your branch, there are a bunch of merge commits. You should probably remove them and rebase on top of master. Then squashing should be easy.

**Comment by emilio** [comment]
Let me know if I can help with that btw. Thanks for your patch!

**Comment by emilio** [comment]
Closing due to inactivity, but feel free to reopen with the issues described above fixed. Thanks!

**Pull request closed without merging**
