### PR TITLE
Add support for associated constants and struct literals

### PR DESCRIPTION
**Pull request by IGI-111**
This solves #100 albeit with some caveats and limitations. Check the commit messages for more details.

### CODE REVIEW

**Comment by kvark** [comment]
This would be very helpful to us at https://github.com/gfx-rs/wgpu
@IGI-111 could you rebase please? other than that, what is blocking this PR from landing?

**Comment by IGI-111** [comment]
The only conflict is fixed, and all the test still pass. This is ready to be merged as far as I'm concerned.

**Comment by kvark** [comment]
Ping @eqrion

**Comment by eqrion** [comment]
The contents of the commits look good to me. @IGI-111 is it possible to rebase the commits to resolve the conflicts instead of doing a merge? If that's done then we can get this added.

**Comment by IGI-111** [comment]
Done @eqrion

**Comment by eqrion** [comment]
@IGI-111 Thanks!

**Pull request merged**
