### PR TITLE
Honor derive_eq / derive_neq for unions.

### PR DESCRIPTION
**Pull request by emilio**
This will make https://bugzilla.mozilla.org/show_bug.cgi?id=1429298 not write it manually.

### CODE REVIEW

**Comment by emilio** [comment]
Done (+test).

**Comment by eqrion** [comment]
Thanks!

**Comment by BorisChiou** [comment]
Awesome!!

**Comment by BorisChiou** [comment]
Probably we have to release a new version of cbindgen so bug 1429298 could use this before landing.

**Pull request merged**
