### PR TITLE
Replaced Items’ String-based names with proper Paths

### PR DESCRIPTION
**Pull request by eqrion**
This is a rebased and updated version of #201.

### CODE REVIEW

**Comment by regexident** [comment]
> @regexident Could you give this a glance? It's your work rebased and updated.

Looks good to me. Thanks for the rebase!

> As far as I can tell, this was a bug that we weren't doing this.

Yes, I stumbled upon it as well.

**Comment by regexident** [comment]
I think the GitHub outage bricked the CI queue. You may have to manually re-trigger Travis-CI.

**Comment by eqrion** [comment]
Fixed and merged. Thanks @regexident!

**Comment by emilio** [comment]
This change should probably have been a breaking change. It made the `include` config option not work on the renamed path, but in the original one, which broke mozilla-central.

I'll update cbindgen on mozilla-central, so no action needed I guess, but wanted to point that out.

**Comment by emilio** [comment]
Hmm, actually I think it may be better if we keep it the way it was... I'll see how hard it is to fix.

**Comment by emilio** [comment]
Actually I think the new behavior is saner, let's keep that, add a test, and I'll take care of all versions building with old cbindgen versions.

**Pull request merged**
