### PR TITLE
Support bulk rename of exported items

### LINKED ISSUE #277: Allow bulk rename of exported items
It should be possible to apply bulk conversions to top-level items (e.g. rename all types to use lowercase snake case).

### PR DESCRIPTION
**Pull request by yshui**
Closes #277

### CODE REVIEW

**Comment by yshui** [comment]
@emilio I indeed am unsure which function to use here. But I think I saw `apply_to_pascal_case` being called with strings that seem to me are not guaranteed to be pascal case, so I thought it was fine.

**Comment by yshui** [comment]
@emilio Do you have suggestions what I should do here?

**Comment by emilio** [comment]
Sure, you should at the very least write some tests that exercise all this code. You can see a bunch of tests using various `cbindgen.toml` options in the `tests/` directory.

Then based on that we can probably see whether the patch itself needs changes or apply_to_pascal_case is just fine.

**Comment by yshui** [comment]
@emilio In the end I settled for adding some heuristics to guess the case of the input string.

**Comment by yshui** [comment]
@emilio Hi, do you think i took the right approach?

**Comment by emilio** [comment]
Hey, yeah, sorry, need to get to review this... I'm not a fan of heuristics generally, but I'll take a closer look.

**Comment by yshui** [comment]
@emilio Any news?

**Comment by yshui** [comment]
Closing in favor of #703

**Pull request closed without merging**
