### PR TITLE
config: Allow to output user-defined stuff in the struct body.

### PR DESCRIPTION
**Pull request by emilio**
This is useful to not make complex struct hard to use in C++ for example.

### CODE REVIEW

**Comment by eqrion** [comment]
Looks good, thanks.

**Comment by eqrion** [comment]
Actually looks like there are some conflicts, could you rebase?

**Comment by emilio** [comment]
Done, will wait for Travis again just in case.

**Comment by eqrion** [comment]
Travis looks good.

**Comment by emilio** [comment]
Thanks!

**Pull request merged**
