### PR TITLE
Implement doc handling for macro expansion

### PR DESCRIPTION
**Pull request by mitsuhiko**
I'm not sure if this is the best way to fix it, but this seems to work quite well. I have no idea how this is supposed to work but obviously one could also fix this in sym.

This fixes https://github.com/eqrion/cbindgen/issues/60

### CODE REVIEW

**Comment by eqrion** [comment]
Would it be possible to make this change in `AnnotationSet::load()` too? Possibly shared if reasonable.

We parse doc strings there, grab the ones with 'cbindgen:', and parse them for commands.

**Comment by mitsuhiko** [comment]
Yes, will adjust that. I wasn't sure what this was doing exactly.

**Comment by mitsuhiko** [comment]
@eqrion changed that. The annotation code is slightly simpler because the slight inaccuracies for whitespace that might matter for doc comments does not apply here.

**Comment by eqrion** [comment]
Awesome, thanks!

**Pull request merged**
