### PR TITLE
ci: Check `cargo test` with minimim supported Rust version

### PR DESCRIPTION
**Pull request by petrochenkov**

### CODE REVIEW

**Comment by petrochenkov** [comment]
https://github.com/eqrion/cbindgen/pull/607 broke `cargo test` on the minimum supported version:
```
error: environment variable `CARGO_BIN_EXE_cbindgen` not defined
Error:   --> tests/profile.rs:43:25
   |
43 |     let cbindgen_path = env!("CARGO_BIN_EXE_cbindgen");
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
cc @jrose-signal

**Comment by jrose-signal** [comment]
Oops. [That's a *Rust* minimum requirement, not a dependency one.](https://blog.rust-lang.org/2020/04/23/Rust-1.43.0.html#new-cargo-environment-variable-for-tests). Should I conditionalize out this test for older Rusts? (Or use a more clunky way of finding the cbindgen executable.)

**Comment by petrochenkov** [comment]
The regular test suite retrieves the path to cbindgen executable the old way, using `OUT_DIR`.
Perhaps `tests\profile.rs` could do the same thing for now?

**Comment by jrose-signal** [comment]
I'll put up a PR later today.

**Comment by jrose-signal** [comment]
Actually, wait, this test is going to fail regardless because it's about expansion, which only works with nightly builds. How does that work with the other expansion tests?

**Comment by petrochenkov** [comment]
`cargo +1.40.0 test nonexistent-test --verbose` here doesn't run any tests, only builds in test mode.

(But when I discovered this, I did run tests, with `RUSTC_BOOTSTRAP=1` :sweat_smile:)

**Comment by jrose-signal** [comment]
Ahh, of course. I didn't think through what that was going to do.

**Comment by emilio** [comment]
Can you rebase this on top of master to confirm it's green? Looks good otherwise.

**Comment by petrochenkov** [comment]
Rebased, CI is green.

**Review by emilio — APPROVED** [review]

**Pull request merged**
