### PR TITLE
Allow excluding monomorph structs in C mode.

### LINKED ISSUE #500: Manually avoid declaring opaque structs
My code uses the following types on the FFI:
```rust
struct Foo(NonZeroU64);
struct Bar {
  foo: Option<Foo>,
}
```
What I want here really is `foo: u64`.

What `cbindgen` ends up producing is:
```cpp
typedef struct Option_Foo Option_Foo;
```

It looks like this opaque type leaves me no way to redefine the binding in the header, or work around otherwise. Is there anything we could to do make this work?

### PR DESCRIPTION
**Pull request by emilio**
Fixes #500.

### CODE REVIEW

**Comment by kvark** [comment]
Trying that on https://github.com/gfx-rs/wgpu/pull/546 I'm getting a new internal panic:
> thread 'main' panicked at 'Unable to mangle generic parameter Ptr(Primitive(UInt8)) for 'Result'', src/bindgen/mangle.rs:52:17

**Comment by emilio** [comment]
Do you have  a stack trace / test-case for that?

**Comment by kvark** [comment]
```
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: cbindgen::bindgen::mangle::internal_mangle_name
   9: cbindgen::bindgen::mangle::internal_mangle_path
  10: cbindgen::bindgen::mangle::mangle_path
  11: <cbindgen::bindgen::ir::opaque::OpaqueItem as cbindgen::bindgen::ir::item::Item>::instantiate_monomorph
  12: cbindgen::bindgen::ir::ty::Type::add_monomorphs
  13: cbindgen::bindgen::ir::typedef::Typedef::add_monomorphs
  14: cbindgen::bindgen::library::Library::instantiate_monomorphs::{{closure}}
  15: cbindgen::bindgen::ir::item::ItemMap<T>::for_all_items
  16: cbindgen::bindgen::library::Library::instantiate_monomorphs
  17: cbindgen::bindgen::library::Library::generate
  18: cbindgen::bindgen::builder::Builder::generate
  19: cbindgen::load_bindings
  20: cbindgen::main
  21: std::rt::lang_start::{{closure}}
  22: std::panicking::try::do_call
  23: __rust_maybe_catch_panic
  24: std::rt::lang_start_internal
  25: std::rt::lang_start
  26: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
make: *** [ffi/wgpu.h] Error 101
graphics35334:wgpu dmalyshau$ 
```
The test case is basically checking out https://github.com/gfx-rs/wgpu/pull/546 and running `make`.

**Comment by emilio** [comment]
I don't get there even:

```
error[E0713]: borrow may still be in use when destructor runs
   --> /home/emilio/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-hal-0.1.0/src/command/render_pass.rs:232:36
    |
189 | impl<'a, B: Backend> RenderPassInlineEncoder<'a, B> {
    |      -- lifetime `'a` defined here
...
232 |         RenderPassSecondaryEncoder(self.0.cmb)
    |         ---------------------------^^^^^^^^^^- returning this value requires that `*self.0.cmb` is borrowed for `'a`
233 |     }
    |     - here, drop of `self` needs exclusive access to `*self.0.cmb`, because the type `command::render_pass::RenderPassInlineEncoder<'_, B>` implements the `Drop` trait

error[E0713]: borrow may still be in use when destructor runs
   --> /home/emilio/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-hal-0.1.0/src/command/render_pass.rs:308:62
    |
262 | impl<'a, B: Backend> RenderPassSecondaryEncoder<'a, B> {
    |      -- lifetime `'a` defined here
...
308 |             RenderPassInlineEncoder(RenderSubpassCommon::new(self.0))
    |             -------------------------------------------------^^^^^^-- returning this value requires that `*self.0` is borrowed for `'a`
309 |         }
310 |     }
    |     - here, drop of `self` needs exclusive access to `*self.0`, because the type `command::render_pass::RenderPassSecondaryEncoder<'_, B>` implements the `Drop` trait

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0713`.
```

**Comment by kvark** [comment]
@emilio I don't think you checked out the right branch of the PR. Your error is from gfx-hal-0.1.0, which is N years old. We just released 0.5 :)

**Comment by emilio** [comment]
Err, whoops :-)

**Comment by emilio** [comment]
```
error[E0599]: no method named `supports_queue_family` found for type `std::option::Option<gfx_backend_vulkan::window::Surface>` in the current scope
   --> wgpu-core/src/instance.rs:308:64
    |
308 | ...                   .map_or(false, |qf| surface.vulkan.supports_queue_family(qf))
    |                                                          ^^^^^^^^^^^^^^^^^^^^^ method not found in `std::option::Option<gfx_backend_vulkan::window::Surface>`

warning: unused import: `window::Surface`
  --> wgpu-core/src/instance.rs:26:5
   |
26 |     window::Surface as _,
   |     ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error
```

**Comment by emilio** [comment]
I'll fix that I guess.

**Comment by kvark** [comment]
To repeat what I wrote in the chat - this patch works for us, and we are eagerly anticipating it to be published. Thank you!

**Pull request merged**
