### PR TITLE
Fixes to support Rust 1.32

### PR DESCRIPTION
**Pull request by jasonish**
- travis-ci: add Rust 1.32 to the build matrix
- Don't use enum variants on type aliases

### CODE REVIEW

**Comment by emilio** [comment]
Ah, the new build is failing, we should probably only run `cargo fmt --check` on nightly: https://travis-ci.org/github/eqrion/cbindgen/jobs/698689169

**Comment by jasonish** [comment]
> Ah, the new build is failing, we should probably only run `cargo fmt --check` on nightly: https://travis-ci.org/github/eqrion/cbindgen/jobs/698689169

Made this fix. However the tests still fail on the older compiler.  Not sure if/when I'll get around to fixing that.

**Comment by emilio** [comment]
Ugh, so...

 * The tests with Cargo.toml v2 format obviously fail. Not sure how we'd mark that as expected.
 * The tests for expand require nightly, see #38

**Comment by petrochenkov** [comment]
@emilio 
1.32 is old at this point and dependencies (`remove_dir_all-0.5.3`) require 1.40 already.

**Comment by emilio** [comment]
Yeah given there are conflicts with this patch and the above, let's close this for now.

**Pull request closed without merging**
